# Generated by Django 4.2.5 on 2023-10-23 11:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('no_of_emp', models.IntegerField(blank=True, null=True)),
                ('type_of_org', models.TextField(blank=True, null=True)),
                ('reg_id', models.TextField(blank=True, null=True)),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('secure_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('company_profile', models.ForeignKey(blank=True, db_column='company_profile', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrkin_customer.companyprofile')),
            ],
            options={
                'db_table': 'customer_user',
            },
        ),
        migrations.CreateModel(
            name='OtpVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('try_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_verify',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('active_users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
                ('is_group', models.BooleanField(blank=True, null=True)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('chat_name', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('from_user', models.ForeignKey(blank=True, db_column='from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrkin_customer.customeruser')),
                ('to_user', models.ForeignKey(blank=True, db_column='to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_to_set', to='wrkin_customer.customeruser')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
                ('company_profile', models.ForeignKey(blank=True, db_column='company_profile', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrkin_customer.companyprofile')),
            ],
            options={
                'db_table': 'designations',
            },
        ),
        migrations.AddField(
            model_name='customeruser',
            name='designations',
            field=models.ForeignKey(blank=True, db_column='designations', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrkin_customer.designations'),
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
                ('unread_users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('is_task', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, db_column='room', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrkin_customer.rooms')),
                ('task', models.ForeignKey(blank=True, db_column='task', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrkin_customer.task')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wrkin_customer.customeruser')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
    ]
